name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Check for changes
        run: |
          git diff --exit-code || echo "Changes detected"

      - name: Commit changes (if any)
        run: |
          git add .
          git commit -m "Auto-update merged filters" || echo "No changes to commit"
          git push || echo "No changes to push"
